env:
  browser: true
  es6: true
  node: true
extends:
  - airbnb-base
  - prettier
  - plugin:vue/recommended
  - plugin:jest/recommended
overrides:
  - files:
      - webpack.*.js
      - postcss.config.js
    rules:
      import/no-extraneous-dependencies:
        - error
        - devDependencies: true
  - files:
      - '*.test.js'
      - '*.test.jsx'
    globals:
      Vue: true
parser: vue-eslint-parser
parserOptions:
  babelOptions:
    rootMode: upward-optional
  ecmaVersion: 7
  jsx: true
  parser: '@babel/eslint-parser'
  requireConfigFile: false
  sourceType: module
plugins:
  - simple-import-sort
  - jest
rules:
  import/no-named-as-default: 'off'
  import/order: 'off'
  no-unused-vars: warn
  simple-import-sort/exports: warn
  simple-import-sort/imports: warn
settings:
  import/resolver: webpack
